// <auto-generated />
using System;
using CareHomeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareHomeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909081739_ChangeMealRecipientToProvider")]
    partial class ChangeMealRecipientToProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareHomeApi.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("PaidDate")
                        .HasColumnType("date")
                        .HasColumnName("paid_date");

                    b.Property<int>("UtilityBillTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("utility_bill_type_id");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("UtilityBillTypeId")
                        .HasDatabaseName("ix_bills_utility_bill_type_id");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("CareHomeApi.Models.CareProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<decimal?>("MonthlySalary")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_salary");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_care_providers");

                    b.ToTable("care_providers", (string)null);
                });

            modelBuilder.Entity("CareHomeApi.Models.CareRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_care_recipients");

                    b.ToTable("care_recipients", (string)null);
                });

            modelBuilder.Entity("CareHomeApi.Models.DutyRotationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("care_provider_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_duty_rotation_entries");

                    b.HasIndex("CareProviderId")
                        .IsUnique()
                        .HasDatabaseName("ix_duty_rotation_entries_care_provider_id");

                    b.ToTable("duty_rotation_entries", (string)null);
                });

            modelBuilder.Entity("CareHomeApi.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_meals_provider_id");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("CareHomeApi.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_notes_provider_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notes_recipient_id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("CareHomeApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CareHomeApi.Models.UtilityBillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_utility_bill_types");

                    b.ToTable("utility_bill_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Su"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Elektrik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Doğalgaz"
                        });
                });

            modelBuilder.Entity("CareHomeApi.Models.Bill", b =>
                {
                    b.HasOne("CareHomeApi.Models.UtilityBillType", "UtilityBillType")
                        .WithMany("Bills")
                        .HasForeignKey("UtilityBillTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_utility_bill_types_utility_bill_type_id");

                    b.Navigation("UtilityBillType");
                });

            modelBuilder.Entity("CareHomeApi.Models.DutyRotationEntry", b =>
                {
                    b.HasOne("CareHomeApi.Models.CareProvider", "CareProvider")
                        .WithMany("DutyRotationEntries")
                        .HasForeignKey("CareProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_duty_rotation_entries_care_providers_care_provider_id");

                    b.Navigation("CareProvider");
                });

            modelBuilder.Entity("CareHomeApi.Models.Meal", b =>
                {
                    b.HasOne("CareHomeApi.Models.CareProvider", "Provider")
                        .WithMany("Meals")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_meals_care_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CareHomeApi.Models.Note", b =>
                {
                    b.HasOne("CareHomeApi.Models.CareProvider", "Provider")
                        .WithMany("Notes")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notes_care_providers_provider_id");

                    b.HasOne("CareHomeApi.Models.CareRecipient", "Recipient")
                        .WithMany("Notes")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notes_care_recipients_recipient_id");

                    b.Navigation("Provider");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CareHomeApi.Models.CareProvider", b =>
                {
                    b.Navigation("DutyRotationEntries");

                    b.Navigation("Meals");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("CareHomeApi.Models.CareRecipient", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("CareHomeApi.Models.UtilityBillType", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
